---
# time-related tasks

- name: install system packages for time management
  apt: pkg=ntp,tzdata state=latest update-cache=yes

- name: set timezone to $timezone
  template: src=templates/etc/timezone dest=/etc/timezone
  notify: update-tzdata
